version: '3'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: connectable-frontend-dev-main:latest
    restart: always
    volumes:
      - /usr/src/.yarn
      - /usr/src/apps/main/.next
      - .:/usr/src
    ports:
      - 3000:3000
