version: '3'

services:
  main:
    build:
      context: .
    image: connectable-frontend-main:latest
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - main
