name: DevSync

on:
  push:
    branches:
      - develop
  delete:
    branches:
      - develop

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.SOURCE_URL }}
          source_branch: 'develop'
          destination_repo: ${{ secrets.DEV_URL }}
          destination_branch: 'develop'
